#configure of patchwatcher

mqserver: localhost
serverip: 10.66.6.19


# jenkins Remote Access configure
# Used to trigger a job via remote access

jenkins_job_url:
jenkins_job_token: 'd6a942ce258932d65ea55e72fc82ae93'
jenkins_job_parameter:
    - CI_PATCH_URL:
        _patchurl_
verify:


# patch label blacklist of trigger patch

label_blacklist:
    - sandbox
    - libvirt-glib
    - gconfig
    - glib
    - libvirt-python
    - libvirt-test-api
    - qemu
    - Qemu-devel
    - libvirt-php
    - libvirt-tck
    - python
