#configure of patchwatcher

# Only support libvirt right now
project_name: "libvirt"
mail_list: "https://www.redhat.com/archives/libvir-list"
git_repo: "git://libvirt.org/libvirt.git"

mqserver: localhost
serverip: localhost


# jenkins Remote Access configure
# Used to trigger a job via remote access

jenkins_job_trigger:
    acceptance_job:
        url:
        token:
        parameter:
            CI_PATCH_URL:
                _patchurl_
        verify:
    unit_test_job:
        url:
        token:
        parameter:
            CI_PATCH_URL:
                _patchurl_
            CI_GIT_COMMIT:
                _git_commit_
        verify:

# patch label blacklist of trigger patch

label_blacklist:
    - sandbox
    - libvirt-glib
    - gconfig
    - glib
    - libvirt-python
    - libvirt-test-api
    - qemu
    - Qemu-devel
    - libvirt-php
    - libvirt-tck
    - python
    - libvirt-perl
